name: poison
run-name: start poison!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    runs-on: macos-latest
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
  
  build:
    runs-on: macos-latest
    steps:
      # 환경 변수 설정
      - name: 'set env'
        run: |
          echo "OTL_HOME=$HOME/.otl" >> $GITHUB_ENV

      # OTLanguage 다운로드
      - name: 'otl install'
        run: |
          echo Install OTL
          curl https://raw.githubusercontent.com/OTLanguage/download/main/mac.sh | sh
        shell: bash
        
      # 모듈 다운로드
      - name: 'install poison model'
        run: | 
          sh $OTL_HOME/otl install poison
        shell: bash
      

      - name: 'test'
        run: |
          ls -al

      # 실행
      - name: 'start'
        run: |
          sh $OTL_HOME/otl start.otl
        shell: bash
