name: poison
run-name: start poison!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: 'otl install'
        run: |
          echo Install OTL
          curl https://raw.githubusercontent.com/OTLanguage/download/main/mac.sh | sh
      - name: 'install poison model'
        run: otl install poison
