name: poison
run-name: start poison!

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 환경 변수 설정
      - name: 'set env'
        env:
          OTL_HOME: ${{ env.HOME }}/.otl
          otl: sh ${{ env.OTL_HOME }}/otl
        run: |
          echo OTL_HOME = $OTL_HOME
          echo otl = $otl
        
      - name: 'otl install'
        run: |
          echo Install OTL
          curl https://raw.githubusercontent.com/OTLanguage/download/main/mac.sh | sh
        shell: bash
        
      - name: 'install poison model'
        run: | 
          otl install poison
        shell: bash
